// Do not edit. This file was generated by scripts/update-ts

const songFestival = [
  {
    "title": "songFestivalRepertoire0",
    "data": [
      183,
      223,
      282,
      72
    ]
  },
  {
    "title": "songFestivalRepertoire1",
    "data": [
      280,
      94,
      87,
      124,
      167,
      339,
      568
    ]
  },
  {
    "title": "songFestivalRepertoire2",
    "data": [
      414,
      25,
      602,
      489,
      37,
      179,
      190,
      155,
      479,
      522,
      156,
      531
    ]
  },
  {
    "title": "songFestivalRepertoire3",
    "data": [
      570,
      76,
      259,
      95,
      611
    ]
  },
  {
    "title": "songFestivalRepertoire4",
    "data": [
      247,
      425,
      616,
      457,
      220,
      121,
      254,
      588
    ]
  }
]

export default songFestival