// Do not edit. This file was generated by scripts/update-ts

const songFestival = [
  {
    "title": "songFestivalRepertoire0",
    "data": [
      175,
      207,
      260,
      69
    ]
  },
  {
    "title": "songFestivalRepertoire1",
    "data": [
      258,
      91,
      84,
      118,
      160,
      312,
      533
    ]
  },
  {
    "title": "songFestivalRepertoire2",
    "data": [
      385,
      25,
      565,
      457,
      34,
      171,
      180,
      148,
      448,
      489,
      149,
      497
    ]
  },
  {
    "title": "songFestivalRepertoire3",
    "data": [
      535,
      73,
      237,
      92,
      574
    ]
  },
  {
    "title": "songFestivalRepertoire4",
    "data": [
      226,
      395,
      578,
      426,
      204,
      116,
      233,
      552
    ]
  }
]

export default songFestival