// Do not edit. This file was generated by scripts/update-ts

const songFestival = [
  {
    "title": "songFestivalRepertoire0",
    "data": [
      174,
      206,
      260,
      68
    ]
  },
  {
    "title": "songFestivalRepertoire1",
    "data": [
      258,
      90,
      83,
      117,
      159,
      312,
      533
    ]
  },
  {
    "title": "songFestivalRepertoire2",
    "data": [
      385,
      24,
      565,
      457,
      33,
      170,
      179,
      147,
      448,
      489,
      148,
      497
    ]
  },
  {
    "title": "songFestivalRepertoire3",
    "data": [
      535,
      72,
      237,
      91,
      574
    ]
  },
  {
    "title": "songFestivalRepertoire4",
    "data": [
      226,
      395,
      578,
      426,
      203,
      115,
      233,
      552
    ]
  }
]

export default songFestival