import { Playlist } from './types';

const dainuSvente: Playlist = {
  id: 'dainu-svente',
  title: 'XI-toji Šiaurės Amerikos Dainų Šventė',
  enTitle: 'XI North American Lithuanian Song Festival',
  items: [
    { title: 'Himnai ir malda', enTitle: 'National Anthems & Prayer' },
    { id: 'recewslcwSSYIe2PB' },
    { id: 'recuJOpnWd8g26at9' },
    { id: 'recmTlEVo5s4u5pvr' },
    { id: 'recTMFKZF1Hx4Moiq' },
    { title: 'Pirma dalis: Lietuviais esame mes gimę', enTitle: 'Part I: We were born Lithuanian' },
    { id: 'recPW0fcbEfCmFP0k' },
    { id: 'recM32f0x5ZHk0FlN' },
    { id: 'receJQKQusXDipRUE' },
    { id: 'recB7wMn4NaF71Uul' },
    { id: 'recTK1ZCvMCH108ak' },
    { id: 'rec68odFNoMq2eDEL' },
    { id: 'rec8GmlbF3hPaffpM' },
    { title: 'Antra dalis: Ten mano svajos...', enTitle: 'Part II: The place of my dreams' },
    { id: 'recBqz3gGNJKzdyY6' },
    { id: 'recZKvAYLouPjkkQO' },
    { id: 'recqeDxAOdq5rt7S1' },
    { id: 'recdZiNMaeBxYDW6q' },
    { id: 'recNO9ohnzBaiZ2SB' },
    { id: 'reckqjzr0X1TKO756' },
    { id: 'recZzgfFkXs5iEdYP' },
    { id: 'recAk1k2DIAQbdpOK' },
    { id: 'recbQR3RMOZ1tuoZA' },
    { id: 'recny2mfxwiL5nRyH' },
    { id: 'recp9NndH1Eyn997v' },
    { id: 'rec7xOQ9CRf2omCah' },
    {
      title: 'Trečia dalis: Jau saulelė vėl atkopdama budino svietą',
      enTitle: 'Part III: And the sun rose, again awakening the world',
    },
    { id: 'rec6lXvZV5qjoBZbl' },
    { id: 'rech5kxtbSjyR8PFj' },
    { id: 'recolsDQwPeOsrvAN' },
    { id: 'recpy4i77fTVhAXzD' },
    { id: 'recWHXdYxKUxGga1Z' },
    {
      title: 'Ketvirta dalis: Atverkime šokio ir dainos skrynelę',
      enTitle: "Part IV: Let's open the hope chest of song & dance",
    },
    { id: 'recAW5oECAOBmqdMh' },
    { id: 'rec6a3gqi9OofeeWV' },
    { id: 'recgoGe6xtPpV2wA5' },
    { id: 'recVPp6MxDEd7ihgo' },
    { id: 'recEcBhvuZ0qL7Jx0' },
    { id: 'recAz8MyNpke2H9sC' },
    { id: 'recns35kTfMWszSdq' },
    { id: 'recdBYkwKgZP5zVB8' },
  ],
};
const systemPlaylists: Playlist[] = [dainuSvente];
export default systemPlaylists;
